---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-operator
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 24h
  url: https://helm.mariadb.com/mariadb-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: mariadb-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-operator-crds
      # version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: mariadb-operator
      interval: 12h
  values:
    installCRDs: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-operator
      # version: "0.24.0"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: mariadb-operator
      interval: 12h
  values:
    installCRDs: true
