---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 24h
  url: https://operator.min.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator
  namespace: minio-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: operator
      version: "7.0.1"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio-operator
      interval: 12h
  values:
    installCRDs: true
