---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb-operator
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mongodb
  namespace: mongodb-operator
spec:
  interval: 24h
  url: https://mongodb.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: community-operator
  namespace: mongodb-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: community-operator
      version: "0.13.0"
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: mongodb-operator
      interval: 12h
  values:
    operator:
      watchNamespace: "*"
