apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: universal-auth-credentials
            namespace: default
          clientSecret:
            key: clientSecret
            name: universal-auth-credentials
            namespace: default
      hostAPI: https://infisical.k.gv.ca
      secretsScope:
        environmentSlug: prod
        expandSecretReferences: true
        projectSlug: home-lab-4b5-c
        recursive: true
        secretsPath: /
