---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: letsencrypt-production-account-key
        metadataPolicy: None
      secretKey: tls.key
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: letsencrypt-email
        metadataPolicy: None
      secretKey: email
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: letsencrypt-production-account-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: letsencrypt-stage
  namespace: cert-manager
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: letsencrypt-stage-account-key
        metadataPolicy: None
      secretKey: tls.key
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: letsencrypt-email
        metadataPolicy: None
      secretKey: email
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: letsencrypt-stage-account-key
