---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: rocketchat
spec:
  members: 1
  type: ReplicaSet
  version: "8.0.6"
  security:
    authentication:
      modes: ["SCRAM", "SCRAM-SHA-1"]
  users:
    - name: rocketchat
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: salt
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: root
          db: admin
        - name: root
          db: rocketchat
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
