---
apiVersion: v1
kind: Namespace
metadata:
  name: infisical
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: infisical
  namespace: infisical
spec:
  interval: 24h
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: infisical
spec:
  interval: 30m
  chart:
    spec:
      chart: infisical-standalone
      version: "1.*"
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: infisical
      interval: 12h
  values:
    infisical:
      image:
        repository: infisical/infisical
        tag: "v0.115.0-postgres"
        pullPolicy: IfNotPresent
      replicaCount: 1
      resources:
        limits:
          memory: 640Mi
        requests:
          memory: 210Mi
          cpu: 200m
    ingress:
      enabled: true
      hostName: "infisical.k.gv.ca"
      ingressClassName: "traefik"
      nginx:
        enabled: false
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
        traefik.ingress.kubernetes.io/router.middlewares: traefik-redirectscheme@kubernetescrd
      tls:
        - secretName: infisical-tls
          hosts:
            - infisical.k.gv.ca
