---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-cnpg
  namespace: gitea
spec:
  instances: 1
  managed:
    roles:
      - name: gitea
        superuser: true
        login: true
  bootstrap:
    initdb:
      database: gitea
      owner: gitea
  storage:
    size: 4Gi
