---
# Source: gitea/templates/gitea/ssh-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: gitea
  labels:
    helm.sh/chart: gitea-12.4.0
    app: gitea
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/version: "1.24.6"
    version: "1.24.6"
    app.kubernetes.io/managed-by: Helm
  annotations: {}
spec:
  type: ClusterIP
  clusterIP:
  ports:
    - name: ssh
      port: 22
      targetPort: 2222
      protocol: TCP
  selector:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-nodeport
  namespace: gitea
spec:
  ports:
    - name: ssh
      nodePort: 32222
      port: 32222
      protocol: TCP
      targetPort: 2222
  selector:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
  sessionAffinity: None
  type: NodePort
